### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by HERUESTA** [HERUESTA/TwitchClipFinder#33]
■Webアプリの概要
TwitchClipFinderは、日本のTwitch配信者のクリップを簡単に検索できるサービスです。配信者名、ゲーム名、日時での検索が可能で、ユーザーは効率的に面白いクリップを見つけ、いいねや共有ができます。現状の課題として、Twitchではクリップ検索に多くのステップが必要で、既存のサービスも配信者IDのみでの検索やデザインの使い勝手に問題があります。これを解決するため、配信者名やゲーム名での検索機能、いいね機能、共有機能を実装します。将来的にはプレイリストやランキング機能を追加予定です。技術スタックはRailsとTurboを使用し、Twitch APIからクリップデータを取得し、SEO対策も行います。このサービスにより、ユーザーは簡単にクリップを検索・共有できるようになります。

■1週間辺りの開発に向けられる時間
- 1週間あたり：20時間（1週間あたり10ストーリーポイントを消化予定）

■ProjectsのURL
https://github.com/users/HERUESTA/projects/7/views/2

■MVPリリースまで
- [ ] rails new
- [ ] fly.ioにデプロイ
- [ ] GitHubAction導入
- [ ] トップページ作成
- [ ] footerページ作成
- [ ] TOP画面Headerページ作成
- [ ] ユーザープロフィール画面Headerページ作成
- [ ] ユーザー登録機能兼ログイン機能（Twitch認証機能）
- [ ] deviseの導入
- [ ] フォローリスト取得機能
- [ ] 配信者名検索機能
- [ ] ゲーム名検索機能
- [ ] いいね機能
- [ ] ユーザープロフィール画面
- [ ] X共有

■MVP後
- [ ] オートコンプリート検索機能
- [ ] 利用規約
- [ ] プライバシーポリシー
- [ ] お問い合わせ
- [ ] RSpec（モデルテスト・システムテスト）
- [ ] ファビコン
- [ ] 独自ドメイン
- [ ] レスポンシブ対応
- [ ] OGP（静的）
- [ ] プレイリスト機能

■MVPレビュー依頼予定日
予定日：2024年 11月 10日

**Comment by tarakish** [comment]
確認しました。LGTMです！
MVPリリースに向けて開発頑張ってください。
